### ISSUE TITLE
Where to specify the sudo user in lsyncd configuration ?

### ISSUE THREAD

**Issue by jitheshpk** [axkibe/lsyncd#201]
settings {
   logfile = "/var/log/lsyncd/lsyncd.log",
   statusFile = "/var/log/lsyncd/lsyncd-status.log",
   statusInterval = 1
}

sync{
       default.rsyncssh,
       source="/home/titech",
       host="192.168.1.99",
       targetdir="/home/ti/www",
}

I can able to connect with remote server without password now by copying the id_rsa.pub file to authorized_keys file

But the remote sync operation not taking place...

In error log i can see
Wed Apr 24 16:08:18 2013 Error: Terminating since out of inotify watches.
Consider increasing /proc/sys/fs/inotify/max_user_watches

Other than this error, did i need to specify my remote sudo username anywhere in master server ?

**Comment by SkinnerJL** [comment]
With the Host key verification failed. error for those that run into it. It generally means that the ssh config isn't working. Either the entry in the known_hosts file is off and the IP has changed on the server, or one of the servers you are using is new and you have to ssh into them and add them to your known_hosts file so that lsync can ssh into the server without getting a prompt and getting hung up on that.

**Comment by silkcom** [comment]
I'm having this same problem.  I can run ssh server.name and it works just fine, but when I try and use lsyncd it gives me the Host key verification failed. line. Very odd.
