### ISSUE TITLE
lsyncd exits silently if logfile does not exist

### ISSUE THREAD

**Issue by strokirk** [axkibe/lsyncd#302]
When `lsyncd` is started with `lsyncd config.lua`, the process will exit silently if the _logfile_ does not exist. 

This is confusing, and an error message should be printed to _stderr_.

Test config file:

``` lua
settings {
  logfile = "/foo/bar.log",
  statusFile = "/foo/baz.log",
  delay = 0
}
sync {
  default.rsync,
  source = os.getenv( "HOME" ) .. "/test/",
  target = os.getenv( "HOME" ) .. "/test2/",
}
```

**Comment by endotoh** [comment]
I have reproduced this error on 2.0.4 RMP (note that I needed equals (=) sign after "settings") in above code block.

Also note that this silent error cod-epath is avoided with -nodaemon option, ie process starts and correctly enters event loop.

**Comment by axkibe** [comment]
The issue is Lsyncd first deamonizes before it starts to try to log anything.

I changed 2.1.7 do say a "Startup, daemoning now" log message, before it daemonizes, so to test logging before it loses stderr to bug about it.. with the effect this startup message is now always visible on stdout as well since it happens before daemonizing. I hope nobody feels pestered by it.
