### ISSUE TITLE
rsync onCompleted

### ISSUE THREAD

**Issue by bymaximus** [axkibe/lsyncd#338]
Hi, I saw is possible to define actions for 'bash', rsync is also possible?

If same actions works with rsync, 'onComplete' is provided too? For example 'onComplete' called after rsync sync completed with some variable which contains the status of sync (completed/error) and also the number of synced files. 

I want for example run remote commands at target server if rsync process completed without error like zip remote target folder, but to do this I need to know if rsync completed without error. Possible?

```code
bash = {
    delay = 5,
    maxProcesses = 3,
    onCreate = "cp -r ^sourcePathname ^targetPathname",
    onModify = "cp -r ^sourcePathname ^targetPathname",
    onDelete = "rm -rf ^targetPathname",
    onMove   = "mv ^o.targetPathname ^d.targetPathname",
    onStartup = '[[ if [ "$(ls -A ^source)" ]; then cp -r ^source* ^target; fi]]',
}
```

**Comment by axkibe** [comment]
The main issue with this request is, how to handle errors on the onComplete action? This complicates things enourmously.

How about using a compressed file system on the target, like ZFS?

**Comment by axkibe** [comment]
An alternative is always to bundle the postprocessing in your onAction script, and have it return an error code if the whole thing was okay, it wants Lsyncd to retry to whole thing, or it wants Lsyncd to terminate.

Otherwise as said, postprocessing as separate step has the issue it would need another layer of error handling from Lsyncd's point of view which would quite complicate things further more
