### ISSUE TITLE
Rsync scan all the directory when the is only one change

### ISSUE THREAD

**Issue by xxorax** [axkibe/lsyncd#340]
When a change happen on one file, rsync scan all the directories to sync the whole paths to the destination server, instead of sync only the changed file.

Here is my conf file :
```
settings = {
        logfile    = "/var/log/lsyncd.log",
        statusFile = "/var/log/lsyncd.status",
        maxDelays = 10
}

sync { 
        default.rsyncssh,
        source="/home/mysite.com/",
        host="other.server.com",
        targetdir="/home/mysite.com/",
        exclude={
                "/.htaccess",
        },
        rsyncOpts={"-rlptogs"}
}
```
I see all the paths written in the lsyncd.status file at each change.

Note that I use lsyncd 2.0.7.
Maybe I mistake somewhere ?

Thanks !

**Comment by Episodio1** [comment]
I don't know what it could be. My lsync (with same SETTINGS config as yours) detect only new files and send incremental changes to remote server.

Maybe LOG file could reveal us anything?

**Comment by axkibe** [comment]
First I suggest updating Lsyncd to a recent version, second "rysncOpts" must not include the '-r' parameter, Lsyncd will add it when its needed.

Since many people configured it wrongly, the 'rsyncOpts' thingy was removed with the 2.1.x release, replaced with a configuration system hopefully less likely to errors of these kinds.
