### ISSUE TITLE
Symbolic link config does not behave as expected

### ISSUE THREAD

**Issue by CImrie** [axkibe/lsyncd#363]
Hi,

When using the archive = true option (in the rsync section of the config file) it does not replicate symbolic links to the new directory as expected. When setting links = true explicitly it also does not work. 
All I get is the message
'Skipping non-regular file /path/to/symlink'

I was able to get around this by using the _extra = {"--links"} option, but thought I should point it out for you.

Note I am using rsyncssh to do remote synchronisation, if that helps.

**Comment by axkibe** [comment]
This is akward, as Lsyncd does specify "-l" when archive or links is true, which is synonymous to --links.

I'ld like to see "lsyncd -log Exec" without the _extra workaround in your case.

However, since is almost a year ago (sorry about that), I close it, if you're still there and interested just reopen please
