### ISSUE TITLE
slow move

### ISSUE THREAD

**Issue by mokraemer** [axkibe/lsyncd#367]
I've seen that move operations get caught and are not translated to rsync which is usefull for large files.
If you have multiple moves as it is in an installation process for each moved file a new ssh connection is created.
I suggest to have multiple moves executed by one connection.

**Comment by axkibe** [comment]
The issue is, while multiple moves could be chained with '&&' operations in the ssh command, how could Lsyncd know in case of failure which ones need a retry and witch ones completed successfully?

Ultimatevely I think this (and other issues) could only be circumvented by having a custom binary running at the target instead of using standard Unix tools.

**Comment by mokraemer** [comment]
why do you want to chain them with && operator. If you chain them with ";" it will continue to the end.
Since the operation is
mv x y||rm -rf x
I don't think there is a need for a "retry", or am I missing sth.?

Running a binary might still be an option - I'm glad lsync works better than tools like "gluster" which have a high demand on VERY fast network connection - even on read, which lead me to your project.

**Comment by axkibe** [comment]
Hmmm, you got a point there.

How does ssh/sshd/bash operate on this if the network breaks, while the chain is running through?

**Comment by mokraemer** [comment]
a) this is a rare condition
b) if networks fails ssh keeps the connection alive for some time (must be tcp timeout ~ 3 min) so commands work until that time - assuming mv won't take that long, you can ignore this as well

**Comment by axkibe** [comment]
While I cannot guarantee it to be 100% the case, one design goal of Lsyncd is 100% race condition free and work fine out of all target host and network fails.

I suppose when the connection breaks, Lsyncd can never know if the other side continued the command (network fail) or stopped (target host fail).

However, it can and should correctly recover from this conditions by forgetting about the 'mv' the stuff and rego a file transfer of all affected files including deleting the mv sources. It is unfortunate to have to send big files over the net, but as you said, it should be a rare condition and better fall back than getting out of sync which can have all kind of follow-up errs.

**Comment by axkibe** [comment]
PS: actually I know its not 100% case with rsyncssh, since there is one known issue if a directy symlink directory is moved and replaced by a real directoy with exactly the same time while the transfer is still going, or the other way around I don't remember without looking the exact issue up, but I don't know a good way around it. plain rsync should be 100% race condition free as far i know.

**Comment by axkibe** [comment]
The issue is, with Lsyncd 2.2.0 and heavy testing I had to turn parallelization even further down to disable all race conditions, since my single blocking event detection logic was just far not enough.

Like changes happening the source of the move after the move was done. This has to be blocking until the target reproduced the move, before the source of the move may be synced.

What I suggest instead is to set up ssh to use persistent connections. That should improve performance for you.
See:
http://unix.stackexchange.com/questions/50508/reusing-ssh-session-for-repeated-rsync-commands

I'll consider setting this up as default behavior for future Lsyncd releases:
https://github.com/axkibe/lsyncd/issues/416
