### ISSUE TITLE
feature request: exit after idle for some time

### ISSUE THREAD

**Issue by dnr** [axkibe/lsyncd#392]
I have a situation that could use this feature: if lsyncd hasn't seen any changes for some configurable time, then exit (and remove its pidfile).

In detail: I have a script that I'm using interactively to run a command on a remote machine, via ssh. I want the current directory on the remote machine to look the same as the local directory. Of course, I could do a full rsync with each run, but I'm using lsyncd as an optimization: before running the command, my script starts lsyncd if it's not running, and then watches its log file to ensure that the sync is up to date. Since I don't need it to be running all the time, and it's harmless if it exits (it just means I have wait a little longer next time I use the script), it would be good if lsyncd could just exit after a while. It would make things much less error-prone if I used the script from multiple sources to the same target, which I'd like to do.

**Comment by axkibe** [comment]
This can be coded with a custom sync configuration. You have the global alarm() call you can ask the Lsyncd kernel to notify your script, when a specified amount of time passed.

Requests like these are why Lsyncd uses a full featured scripting Language like Lua since version 2.0. You need it? you can add it.

**Comment by axkibe** [comment]
PS: Notify me when you want are going that route, and need a little help.
