### ISSUE TITLE
Lsyncd and Amazon EFS

### ISSUE THREAD

**Issue by paul-norman** [axkibe/lsyncd#401]
I have been using Lsyncd successfully with an Amazon EFS drive mounted to a single server for a while now, but I have noticed that if I mount the EFS drive to a second server and launch a second Lsyncd daemon to watch the same folder from there then the two servers only sync the changes that they make themselves.

I presume this is because inotify events are at the kernel level and since there's no server that I can control behind EFS I can't forward the events on from there to other observers. Annoyingly there are far too many files for a simple cron calling rsync on the whole data set to be a useful option (as it takes minutes to run each time).

What I ultimately want is a dynamic pool of servers (unknown to one-another) which can all write files to a directory, but this directory be kept in sync across all of them. If EFS weren't so slow it would fulfil this requirement already, but for web apps the files really need bringing onto the local SSD for speed. (Redis et al are not options as they are far too slow for the number of included files).

Are there any options for this scenario?

Thanks in advance!

---

As each machine will not know of its peers, my only thought for a solution is quite long, convoluted and requires a cron in addition to Lsyncd... 

An extra folder is created on the network drive, "/EFS/changes/", and each server writes the file paths that it changes (triggered by Lsyncd) to this directory within a folder containing its hostname (using a bash script), i.e. a structure like:

&nbsp;&nbsp;&nbsp;&nbsp;/EFS/changes/host-1.domain.tld/2016-10-10-18:21 
&nbsp;&nbsp;&nbsp;&nbsp;/EFS/changes/host-1.domain.tld/2016-10-10-18:22
&nbsp;&nbsp;&nbsp;&nbsp;/EFS/changes/host-2.domain.tld/2016-10-10-18:19

etc. And then a cron running on each server scans these folders, compiles a list of changed files from all of them (apart from their own) and calls rsync with the list as arguments. The cron could also remove any files older than X minutes as these should have been used by all servers by then. This avoids initialising a full rsync scan of all EFS contents each time.

**Comment by axkibe** [comment]
Yes, the kernel doesn't send events on network mounted drives. I know of no network filesystem that does this.

If I understand your situation correctly, one idea would be have all the servers connect to an IRC channel (either an IRC server by you, or a public one allowing a password protected channel) and tell there what they changed, so other servers can copy the changes over. I suppose public won't work tough, as you will be gagged for flooding. However I get it, you don't want one specific node keeping running as master to connect the others right? Or you make a hybrid solution, like writing a change file. And telling the other nodes, there is a change file on IRC... and scale this down to do it at most say every 30 seconds or so.

Code fragments are available in the examples directory "lsayirc.lua", that one simply writes to an IRC channel the inotify events it sees. It was an idea back then for servers to stay in sync that cannot connect to each other due to both being behind NAT firewalls. But beyond the simple "telling" example, the code was never futher developed.

Anyway it will be suitable coding job to do.

Or you simply make polling with a tool like Unison or rdiff-backup, that keeps a database of timestamps and does a full rescan of the tree each time instead of relying on notification events like Lsyncd does.

**Comment by paul-norman** [comment]
Thanks for the quick reply, Axel. It's really helpful!

I hadn't considered an IRC channel at all, but there are many conceptually similar options and that example gives me something to start from. Ideally none of the servers would know of the others which makes a private IRC (or similar) server trickier to do and why I was thinking of just writing to a different folder on the same EFS drive with a changelog of sorts.

I'll have a play about with a few options this week and let you know if I come up with something stable for this scenario.

Thanks again!

**Comment by whereisaaron** [comment]
@paul-norman if you mount EFS through an NFS proxy,
e.g. https://github.com/nfs-ganesha/nfs-ganesha/wiki/PROXY
then the proxy can be instrumented to raise events for changes files. If every client mounting the EFS volume is using the proxy (either a shared proxy per AZ or a local one per machine) then you can publish the events to a shared queue (e.g. Kenesis), then consume the combined event queue on each machine. I don't know if you can turn those events into synthetic `inotify` events, or otherwise inform lsyncd.
