### ISSUE TITLE
Handling for hard links?

### ISSUE THREAD

**Issue by eferreira** [axkibe/lsyncd#404]
Hi, I'm trying to use lsyncd to sync a directory where some of the files inside are hard links to each other. Presently, they get copied as separate files on the destination. Is there some way to keep them as hard links on the destination? Would it be enough to pass -H as an extra rsync option or would that cause issues on the incremental rsyncs? If so, how hard would it be to add this feature?

**Comment by axkibe** [comment]
As hard as it is to figure all all hardlinks of a file.

Which is hard, since you have to make a recursive scan of the filesystem.

**Comment by eferreira** [comment]
Ok, yeah, I see that it's kind of complicated. Currently it seems like lsyncd doesn't even properly keep hardlinked files in sync. They become copies on the destination, but then when the hardlinked files change on the source, only one of the paths gets synced to the destination and the other path becomes out of date.

Actually on second thought I think I don't really need this anyway. Thanks.

**Comment by axkibe** [comment]
Lsyncd knows only what The kernel tells it. That is a file in directory X changed. Neither Lsyncd nor The kernel know of hardlinks without having to search for them.

Lsyncd optimizes work for rsync for incremental syncs by telling rsync what files need changing. So it doesn't see the hardlinks as well.

Is there some issue with symlinks? Because they haven't that issues.

**Comment by eferreira** [comment]
What I observed with hardlinks is that if file1 and file2 are hardlinked and they are both inside of the source directory that I'm syncing, then when I modify one file or the other (e.g. by doing 'echo >>file1' or 'echo >>file2' in bash), lsyncd only tries to sync file1. I would have expected it to get notified that file1 and file2 both changed and try to sync both paths. For some reason that wasn't happening and it only ever tries to sync file1. I don't know if it's an issue with inotify or what.

I haven't noticed any issues with symlinks. I think they work fine.

**Comment by axkibe** [comment]
If you edit it by opening file1 it will only get notified that file1 has changed.

Even the kernel doens't know of file2. It only knows that file1 has one other path linking to it (so it can physically free it's blocks when the count reaches 0) but there isn't a list of paths that lead to the file.

Its the way ext2/3/4 works...

**Comment by eferreira** [comment]
Oh, yeah, you're right, it tries to sync file1 or file2 depending on which path I used to modify the file. I read the logs wrong. So there you have it. With hard links we can essentially get a certain file to change contents without the kernel triggering any notification that it happened. So I guess it's pretty much impossible for any incremental sync tool to handle that situation correctly.

**Comment by axkibe** [comment]
Ja, hardlinks come with issues, also in other areas. 

I suggest there was a motivation behind it, why symlinks were invented.

**Comment by nbercher** [comment]
If one runs `rsync -aH src/ [remote:]mirror` each time a hard link has been created or changed in src/ (like discussed above), one gets updated hard links as appropriate in mirror/.
The things is that rsync can achieve this while lsync cannot because lsyncd is somehow path-based and works on individual path component changes. On the other hand, the rsync example above works well because it maintains a list of all of the hard links it encounters under the whole src/ tree in order to replicate it into mirror/.
What might miss to lsyncd then would be to watch the files tree more globally. In this respect, I would argue for lsync to maintain src/'s hard links list in some way in order to properly replicate it to the mirror. Or for example, and more precisely, to have a separate set of settings for this specific purpose like `watch_hard_links = true`, `watch_hard_links_periodicity = 3h` from which to trigger `rsync -H` regularly.
It might be enough and an acceptable compromise.
Also, for the time being, this lack of complete hard links support shall be documented, e.g., in the comment column of the rsync's `hard_link` option in [1], saying that this option is only used by rsync, thus at init time (if my understanding is correct).
[1] https://axkibe.github.io/lsyncd/manual/config/layer4/

**Comment by Gunstick** [comment]
I made a kludge which kind of works. For each file created it will run a find over the whole directory. But you will get hard links on destination
`
SDIR=/tmp/i
ODIR=/tmp/o
lsyncd -nodaemon -log all -direct "$SDIR" "$ODIR" |  
while read a;  
do
  if grep "New Create:" <<<"$a";    
  then
    a="$(cut -d" " -f5- <<<"$a")";   
    cd "$SDIR";
    other="$(find . -inum $(stat --printf "%i" ."$a") | fgrep -v ."$a" | head -1)"; 
    cd "$ODIR"; 
    set -x; 
    ln -f "$other" ."$a";
    set +x; 
  fi;
done
`

**Comment by Al2Klimov** [comment]
lsyncd, when the kernel notifies it about X, seems to invoke rsync with --include-from=-, passing only X to -, and --exclude=*. That way, hard links get lost, even with `rsync.hard_links = true`.

In contrast, if lsyncd wouldn't pass those options, rsync would sync everything and cover hard links properly. Sounds like a good compromise, at least for `rsync.hard_links = true`.

**Comment by Al2Klimov** [comment]
Alternatively, enabling the crontab feature should do it as well.
