### ISSUE TITLE
Does lsyncd watch excluded files?

### ISSUE THREAD

**Issue by marcushat** [axkibe/lsyncd#406]
Does Lsyncd watch files excluded in the sync {} settings?

I'm trying to use this to backup the binary logs of on a very active mysql database.
I know I can do "-include='/mysql_binlog_*'" to and it will only sync these specific files but I'm concerned about using inotify with 1000s of writes a second. If I exclude files will they still be watched?
Or even better is there a way I can not listen to the directory and just use the timer?

**Comment by axkibe** [comment]
Lsyncd puts watch marks on directories, not files.

As long there isn't a bug I'm not aware of, it will not put watches on directories that are excluded fully, however if you exclude only some files from a directory, it will put a mark on that directory thus also receiving all events regarding the excluded files but discarding them instead of forwarding them to rsync.
