### ISSUE TITLE
Crashed with error Cannot assign new key "alarm" to Delay

### ISSUE THREAD

**Issue by sjohndavid** [axkibe/lsyncd#452]
Hi,
I am using lsyncd for the last 5 months. But Lsyncd crashed 4 times with the following error. I could not figure out the cause. Stacktrace is provided below. 

```
Mon Jun  5 05:10:03 2017 Normal: Retrying (list): 255
Mon Jun  5 05:10:03 2017 Error: in Lua: /usr/src/lsyncd-master/lsyncd.lua:687: Cannot assign new key "alarm" to Delay
Mon Jun  5 05:10:03 2017 Error: Backtrace 1 :[C]:-1
Mon Jun  5 05:10:03 2017 Error: Backtrace 2 :/usr/src/lsyncd-master/lsyncd.lua:687
Mon Jun  5 05:10:03 2017 Error: Backtrace 3 :/usr/src/lsyncd-master/lsyncd.lua:2186
Mon Jun  5 05:10:03 2017 Error: Backtrace 4 :/usr/src/lsyncd-master/lsyncd.lua:4273
```

If you need further information please let me know.

Thanks

**Comment by rik78** [comment]
It seems alarm=true is missing in Delay assignAble property.

**Comment by axkibe** [comment]
However, alarm should not be assigned. That was the point of throwing the error if it was tried to, since the code got a bit more structured.

Anyway, you didn't write the release or master git revision, I looked threw the last few releases and none matched a line that could raise this error. I believe this has since been fixed anyway.

Please reopen if this still happens with Lsyncd 2.2.2
