### ISSUE TITLE
partial rsync not retried

### ISSUE THREAD

**Issue by cyounkins** [axkibe/lsyncd#475]
At https://github.com/axkibe/lsyncd/blob/master/default.lua#L340

It says
```
	-- partial transfers are ok, since Lsyncd has registered the event that
	-- caused the transfer to be partial and will recall rsync.
	[  23 ] = 'ok',
	[  24 ] = 'ok',
```

When rsync returns exit code 23 "some files could not be transferred", lsyncd seems to forget about it, does not retry the rsync command or include the failed file in the next rsync invocation. You can simulated exit code 23 by changing a directory's permission to be root:root and XX0 permissions. 

Is this the intended behavior? The comment seems to indicate it should retry. Where is the logic that registers the event as partial?

Thanks for great software!

**Comment by cyounkins** [comment]
Unfortunately the workaround reference here: https://groups.google.com/forum/#!searchin/lsyncd/exitcodes%7Csort:date/lsyncd/D_MR3BAEMIo/2_Blbrx8BQAJ

does not appear to help:
```
sync {
  default.rsyncssh,
  source="/Users/cyounkins/code/av/source/offboard",
  targetdir="/home/cyounkins/code/av/source/offboard",
  host=host,
  delay=delay,
  rsync=rsync,
  exitcodes={
    _merge = true,
    _verbatim = true,
    [   0 ] = 'ok',
...
    [  23 ] = 'again',
    [  24 ] = 'again',
...
  }
}
```

The same behavior occurs. While it says startup, the log line may be relevant:
`16:42:31 Normal: Startup of "/foo/bar/" finished: 23`

**Comment by axkibe** [comment]
The thing is, usually when the source changes during the rsync, it will come up with exactly this, error level 23. This is an error Lsyncd can ignore, since whatever caused the source change, created a Delay/Event in Lsyncd and it will recall rsync for this anyway.

About your case, I get it, you changed it to something so rsync didn't have the permissions to sync it? Well in that case this would be a permanent error and retrying not the suitable answer as well.
