### ISSUE TITLE
Thousands of log messages: "Normal: waiting for 1 more child processes."

### ISSUE THREAD

**Issue by axkibe** [axkibe/lsyncd#93]
Originally filed by silfr...@gmail.com on 2011-11-11T03:29:01

I have a large directory tree (hundreds of thousands of directories) that I was trying to get to sync w/ lsyncd but the initial rsync process takes a very long time.  I think because of this, things get really gummed up with inotify and lsyncd and I end up getting hundreds of these messages per-second while rsync + ssh are running:

Thu Nov 10 22:20:20 2011 Normal: waiting for 1 more child processes.

**Comment by onedayhk** [comment]
I'm on lsyncd 2.2.2 (CENTOS 7) - with millions of files... We have a directory of cached files that we need to sync to different servers and sometimes when these cache files are being re-generated and we try to sync to 3 different servers at the same time then we get a traffic jam.. 

Log is as follows:-
Wed Oct  9 15:38:03 2019 Normal: --- HUP signal, resetting ---
Wed Oct  9 15:38:27 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:39:28 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:40:32 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:41:33 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:42:33 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:43:35 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:44:36 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:45:38 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:46:40 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:47:41 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:47:46 2019 Normal: --- OVERFLOW in event queue ---
Wed Oct  9 15:47:46 2019 Normal: --- HUP signal, resetting ---
Wed Oct  9 15:48:44 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:49:45 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:50:48 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:51:50 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:52:53 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:53:56 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:54:57 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:55:57 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:57:00 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:58:01 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 15:59:05 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 16:00:06 2019 Normal: waiting for 1 more child processes.
Wed Oct  9 16:00:40 2019 Normal: --- OVERFLOW in event queue ---
Wed Oct  9 16:00:40 2019 Normal: --- HUP signal, resetting ---

**Comment by SpyPower** [comment]
Ubuntu 18.04
Lsyncd version 2.2.3
rsync version 3.1.2
This issue is still happening when i try to stop the lsyncd service via systemctl
Sat Mar 28 11:44:03 2020 Normal: --- TERM signal, fading ---
Sat Mar 28 11:44:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:44:04 2020 Normal: --- TERM signal, fading ---
Sat Mar 28 11:45:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:46:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:47:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:48:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:49:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:50:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:51:03 2020 Normal: waiting for 10 more child processes.
Sat Mar 28 11:52:03 2020 Normal: waiting for 10 more child processes.
with ps aux | grep 'lsyncd\|rsync' we can see that the rsync are not stopping as it should, and instead i am forced to sudo kill -9 `pidof rsync` to stop the service.
